In [1]:
import os
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

In [5]:
df_messy = pd.read_csv(os.path.join('data', 'column_headers_are_values.csv'), sep=' ')
df_messy

                  religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  $50-75k
0                 Agnostic     27       34       60       81       76      137
1                  Atheist     12       27       37       52       35       70
2                 Buddhist     27       21       30       34       33       58
3                 Catholic    418      617      732      670      638     1116
4       Don’t know/refused     15       14       15       11       10       35
5         Evangelical Prot    575      869     1064      982      881     1486
6                    Hindu      1        9        7        9       11       34
7  Historically Black Prot    228      244      236      238      197      223
8        Jehovah’s Witness     20       27       24       24       21       30
9                   Jewish     19       19       25       25       30       95

In [10]:
df_messy[df_messy.religion == 'Buddhist'][['$10-20k','$20-30k','$30-40k']].sum(axis=1).values[0]

85